"""
Configuración global del juego
Contiene todas las constantes y configuraciones centralizadas
"""

# === CONFIGURACIÓN DE PANTALLA ===
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
FPS = 60

# === CONFIGURACIÓN DE COLISIONES ===
COLLISION_BLOCK_SIZE = 32

# === CONFIGURACIÓN DE COLORES ===
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
GRAY = (128, 128, 128)
DARK_GRAY = (64, 64, 64)

# === CONFIGURACIÓN DE PERSONAJES ===
CHARACTER_SPEED = 5
CHARACTER_SIZE = (64, 64)
HEALTH_BAR_WIDTH = 100
HEALTH_BAR_HEIGHT = 10

# === CONFIGURACIÓN DE ANIMACIONES ===
ANIMATION_SPEED = 0.15
FRAME_DURATION = 100

# === CONFIGURACIÓN DE AUDIO ===
MASTER_VOLUME = 0.7
MUSIC_VOLUME = 0.5
SFX_VOLUME = 0.8

# === CONFIGURACIÓN DE ITEMS ===
ITEM_SIZE = (32, 32)
ITEM_SPAWN_RATE = 0.02
MAX_ITEMS = 10
ITEM_DESPAWN_TIME = 30000  # 30 segundos

# === CONFIGURACIÓN DE ENEMIGOS ===
WORM_SPEED = 2
WORM_HEALTH = 100
WORM_DAMAGE = 20

# === CONFIGURACIÓN DE ATAQUES ===
ATTACK_COOLDOWN = 500  # milliseconds
ATTACK_DAMAGE = 25
ATTACK_RANGE = 100

# === RUTAS DE ARCHIVOS ===
ASSETS_PATH = "assets/"
SOUNDS_PATH = "assets/sounds/"
MUSIC_PATH = "assets/music/"
CHARACTERS_PATH = "assets/characters/"
BACKGROUNDS_PATH = "assets/backgrounds/"
ANIMATIONS_PATH = "assets/animations/"

# === CONFIGURACIÓN DE GUARDADO ===
SAVE_FILE = "game_save.dat"
AUTO_SAVE_INTERVAL = 60000  # 60 segundos

# === CONFIGURACIÓN DE DESARROLLO ===
DEBUG_MODE = False
SHOW_FPS = True
SHOW_HITBOXES = False